<?php

namespace Dwr\FrontendBundle\Entity;

use Dwr\FrontendBundle\Entity\CustomRepository;

/**
 * GrammaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrammaryRepository extends CustomRepository
{

}
