<?php

namespace Dwr\FrontendBundle\Entity;

use Dwr\FrontendBundle\Entity\CustomRepository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends CustomRepository
{

    public function findWordsIdByPart($part)
    {
        $qb = $this->createQueryBuilder('w')
                ->select('w.id')
                ->where('w.part = ?1')
                ->setParameter(1, $part->getId())
                ->getQuery();

        return $qb->getResult();
    }
    
    public function findRandomWords($number)
    {
        $wordsQuery = $this->createQueryBuilder('w');
        $query = $wordsQuery->select('w.english')
            ->add('where', $wordsQuery->expr()->in('w.id', '?1'))
            ->setParameter(1, $this->getRandomWordsId($number))
            ->getQuery();

        return $query->getResult();
    }
    
    private function getRandomWordsId($number)
    {
        $ids = $this->createQueryBuilder('w')
                ->select('w.id')
                ->getQuery()->getResult();
        
        shuffle($ids);
        $randomIds = array_slice($ids, 0, $number);
        
        $randomWordsId = array();
        foreach ($randomIds as $id) {
            $randomWordsId[] = $id['id'];
        }
        
        return $randomWordsId;
    }
}
