<?php

namespace Dwr\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{
    /**
     * 
     * @param Entity $entity
     * @param string $column
     * @return type
     */
   public function findAllFromColumn($entity, $column){
       
       $em = $this->getEntityManager();
       $qb = $em->createQueryBuilder();
       $qb->select('entity.'.$column)
          ->from($entity, 'entity')
          ->groupBy('entity.'.$column);
          
       return $qb->getQuery()->getResult();
   }
}
