<?php

namespace Dwr\FrontendBundle\Entity;

use Dwr\FrontendBundle\Entity\CustomRepository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends CustomRepository
{

    public function findWordsIdByPart($part)
    {
        $qb = $this->createQueryBuilder('w')
                ->select('w.id')
                ->where('w.part = ?1')
                ->setParameter(1, $part->getId())
                ->getQuery();

        return $qb->getResult();
    }
}
